### ISSUE TITLE
Is it work when app close?

### ISSUE THREAD

**Issue by channelntltv** [DevEddy/Plugin.Geofencing#4]
Thank for you contribute! 
1. Is it work when app close?
2. Please add UWP!

**Comment by DevEddy** [comment]
Hi @channelntltv 
1. With a foreground service, yes
2. Do you have any resources?

-- Eddy

**Comment by channelntltv** [comment]
@DevEddy 
I'm working with UWP from Xamarin.Forms. Could you please support UWP!
Thank!

**Comment by DevEddy** [comment]
Hi @channelntltv 

You should take a look at https://github.com/shinyorg/shiny

-- Eddy
